name: Preceding Tag Action
author: AJ Granowski
description: Find the most recent tag that is reachable from a commit.
branding:
  color: orange
  icon: git-merge

runs:
  using: node24
  main: dist/index.js

inputs:
  default-tag:
    description: The default tag to return if no preceding tag was found.
    default: ""
    required: false
  include-ref:
    description: If true, include tags pointing to `ref` as candidates.
    default: "false"
    required: false
  ref:
    description: The branch, tag, or SHA to find the preceding tag from.
    default: ${{ github.sha }}
    required: true
  regex:
    description: A regular expression used to filter candidate tag names.
    default: ^.+$
    required: false
  repository:
    description: Repository name with owner. For example, AJGranowski/preceding-tag-action
    default: ${{ github.repository }}
    required: false
  token:
    description: Personal access token (PAT) used to fetch the tags.
    default: ${{ github.token }}
    required: false

outputs:
  tag:
    description: The preceding tag, or `default-tag` if no preceding tag matching the filter was found.
  tag-found:
    description: True if the preceding tag was found. False if the `default-tag` fallback was used.