name: Preceding Tag Action
description: Finds the most recent tag matching the given pattern that is reachable from this commit.
runs:
  using: node24
  main: dist/index.js

inputs:
  filter:
    description: A regular expression used to filter candidate tag names.
    default: ^.+$
    required: true
  ref:
    description: The branch, tag, or SHA to find the preceding tag from.
    default: ${{ github.sha }}
    required: true
  repository:
    description: Repository name with owner. For example, AJGranowski/preceding-tag-action
    default: ${{ github.repository }}
    required: true
  token:
    description: Personal access token (PAT) used to fetch the tags.
    default: ${{ github.token }}
    required: true

outputs:
  tag:
    description: The preceding tag, or an empty string if no preceding tag matching the filter was found.