name: CI/CD

on:
  create:
  workflow_dispatch:
  push:
    branches:
      - "**"
      - "!dependabot/**"
    tags:        
      - "**"
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  workflow-filter:
    name: Workflow Filter
    runs-on: ubuntu-latest
    outputs:
      run-ci: ${{ (github.event_name == 'workflow_dispatch' || github.ref_type == 'tag' || steps.ci-files-changed.outputs.paths_any_modified == 'true') && !startsWith(github.ref, 'refs/tags/v') }}
      run-release-bump: ${{ github.ref == 'refs/heads/main' && env.COMMIT_IS_TAGGED != 'true' && env.SKIP_AUTO_RELEASE != 'true' && steps.release-source-files-changed.outputs.paths_any_modified == 'true' }}

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
      with:
        disable-sudo: true
        egress-policy: audit
        allowed-endpoints: >
          github.com:443

    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Check for Tag
      run: |
        if git describe --contains "$GITHUB_SHA"; then
          echo 'COMMIT_IS_TAGGED=true' >> "$GITHUB_ENV";
        else
          echo 'COMMIT_IS_TAGGED=false' >> "$GITHUB_ENV";
        fi

    # Maybe one day GitHub will handle this for us using path filters, but for now we need to skip all of the steps that would normally run for non-code changes ourselves.
    # https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks
    - name: CI Files Changed
      id: ci-files-changed
      if: ${{ github.event_name != 'workflow_dispatch' && github.ref_type != 'tag' }}
      uses: step-security/changed-files@95b56dadb92a30ca9036f16423fd3c088a71ee94 # v46.0.5
      with:
        files_yaml: |
          paths:
            - "**"
            - "!*.md"
            - "!.github/**"
            - ".github/workflows/cicd.yml"

    - name: Check for \#skip-auto-release
      run: |
        case "$(git show -s --format=%b "$GITHUB_REF")" in
          *#skip-auto-release*) echo 'SKIP_AUTO_RELEASE=true' >> "$GITHUB_ENV";;
        esac

    - name: Release Source Files Changed
      id: release-source-files-changed
      if: ${{ github.event_name != 'workflow_dispatch' && github.ref_type != 'tag' }}
      uses: step-security/changed-files@95b56dadb92a30ca9036f16423fd3c088a71ee94 # v46.0.5
      with:
        files_yaml: |
          paths:
            - "action.yml"
            - "cjs-shim.mjs"
            - "esbuild.config.mjs"
            - "package.json"
            - "src/**"

  ci:
    name: CI
    runs-on: ubuntu-latest
    needs: workflow-filter
    if: ${{ needs.workflow-filter.outputs.run-ci == 'true' }}
    strategy:
      matrix:
        script: ["bundle", "check-types", "lint", "test"]

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
      with:
        disable-sudo: true
        egress-policy: audit
    
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Validate Compose File
      run: docker compose --file compose.yml config --quiet
    
    - name: Run ${{ matrix.script }}
      env:
        SCRIPT: ${{ matrix.script }}
      run: |
        ./npm -- clean-install
        ./npm -- run "$SCRIPT"

    - name: Store Bundle Artifacts
      if: ${{ matrix.script == 'bundle' }}
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: bundle
        path: dist/
        if-no-files-found: error

    - name: Install Node
      if: ${{ matrix.script == 'bundle' }}
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: lts/*

    - name: Bundle Regression Test (1/3)
      id: execute-bundle
      if: ${{ matrix.script == 'bundle' }}
      run: npm run run-bundle

    - name: Bundle Regression Test (2/3)
      id: preceding-tag
      uses: AJGranowski/preceding-tag-action@c08b66c48d658f029e6e5458df2ce186b99f28af # v0.0.0

    - name: Bundle Regression Test (3/3)
      if: ${{ matrix.script == 'bundle' }}
      env:
        BUNDLE_TAG: ${{ steps.execute-bundle.outputs.tag }}
        PRECEDING_TAG: ${{ steps.preceding-tag.outputs.tag }}
      run: |
        [ "$BUNDLE_TAG" = "$PRECEDING_TAG" ] || true

  release-bump:
    name: Bump Release Tag
    runs-on: ubuntu-latest
    needs: [workflow-filter, ci]
    concurrency:
      group: release-bump
    permissions:
      contents: write
    env:
      RELEASE_REGEX: ^release-(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)$

    if: ${{ needs.workflow-filter.outputs.run-release-bump == 'true' }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Get Preceding Release Tag
        id: preceding-tag
        uses: AJGranowski/preceding-tag-action@c08b66c48d658f029e6e5458df2ce186b99f28af # v0.0.0
        with:
          filter: ${{ env.RELEASE_REGEX }}

      - name: Increment And Create Release Tag
        id: increment-tag
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          PRECEDING_RELEASE_TAG: ${{ steps.preceding-tag.outputs.tag }}
          RELEASE_REGEX: ${{ env.RELEASE_REGEX }}
        with:
          script: |
            core.info(`PRECEDING_RELEASE_TAG: ${process.env.PRECEDING_RELEASE_TAG}`);
            core.info(`RELEASE_REGEX: ${process.env.RELEASE_REGEX}`);
            const regexp = new RegExp(process.env.RELEASE_REGEX);
            const groups = process.env.PRECEDING_RELEASE_TAG.match(regexp).groups;

            // Convert string to number
            Object.keys(groups).forEach((key) => {
              let value = groups[key];
              let parsedValue = parseFloat(value);
              if (parsedValue.toString() === value) groups[key] = parsedValue;
            });

            const bumpedTag = `release-${groups.major}.${groups.minor}.${groups.patch + 1}`;
            if (!regexp.test(bumpedTag)) {
              throw new Error(`Bumped tag does not match RELEASE_REGEX "${bumpedTag}"`)
            }

            const bumpedRef = `refs/tags/${bumpedTag}`;

            await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: bumpedRef
            }).then((response) => {
              throw new Error(`Tag already exists: ${bumpedRef}`);
            }).catch((e) => {
              if (e != null && e.status !== 404) throw e;
            });

            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: bumpedRef,
              sha: process.env.GITHUB_SHA
            });

            core.info(`Created tag: ${bumpedRef}`);

  pre-release:
    name: Pre-Release
    runs-on: ubuntu-latest
    needs: [workflow-filter, ci]
    concurrency:
      group: release-${{ github.ref }}
    permissions:
      contents: write
    outputs:
      version-tag: ${{ fromJson(steps.create-version-tag.outputs.result) }}

    if: ${{ startsWith(github.ref, 'refs/tags/release-') && needs.workflow-filter.outputs.run-release-bump != 'true' }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          disable-sudo: true
          egress-policy: audit
      
      - name: Create Version Tag
        id: create-version-tag
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          GITHUB_REF: ${{ env.GITHUB_REF }}
          GITHUB_SHA: ${{ env.GITHUB_SHA }}
        with:
          script: |
            const vTag = process.env.GITHUB_REF.replace("refs/tags/release-", "refs/tags/v");
            await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: vTag
            }).then((response) => {
              throw new Error(`Tag already exists: ${vTag}`);
            }).catch((e) => {
              if (e != null && e.status !== 404) throw e;
            });

            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: vTag,
              sha: process.env.GITHUB_SHA
            });

            return vTag.substring("refs/tags/".length);

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Download Bundle Artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: bundle
          path: dist/

      - name: Create and Tag Release Commit
        uses: JasonEtco/build-and-tag-action@dd5e4991048c325f6d85b4155e586fc211c644da # v2.0.1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ fromJson(steps.create-version-tag.outputs.result) }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: pre-release
    concurrency:
      group: release-${{ github.ref }}
      cancel-in-progress: true

    if: ${{ startsWith(github.ref, 'refs/tags/release-') }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        disable-sudo: true
        egress-policy: audit

    - name: Create Release
      run: echo 'Create a release using the ${{ needs.pre-release.outputs.version-tag }} tag.'