name: Fuzz Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  fuzz:
    name: Fuzz Tests
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          auth.docker.io:443
          dl-cdn.alpinelinux.org:443
          github.com:443
          production.cloudflare.docker.com:443
          production.cloudfront.docker.com:443
          registry-1.docker.io:443
          registry.npmjs.org:443
          release-assets.githubusercontent.com:443

    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Validate Compose File
      run: docker compose --file compose.yml config --quiet

    # https://docs.docker.com/build/ci/github-actions/cache/#github-cache
    - name: Set up Docker CLI
      id: setup-buildx-action
      uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
      with:
        name: fuzz

    - name: Docker Cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: /tmp/buildkit-cache
        key: buildkit-${{ runner.os }}-${{ hashFiles('./container-images/**') }}

    - name: Build Docker images
      uses: docker/bake-action@d3418bd7d0e9324001bca92fa8ba175ea7e6dc9b # v7.3.0
      with:
        allow: |
          network.host
        builder: ${{ steps.setup-buildx-action.outputs.name }}
        load: true
        set: |
          *.cache-from=type=local,src=/tmp/buildkit-cache
          *.cache-to=type=local,dest=/tmp/buildkit-cache,mode=max
        source: .

    - name: NPM Cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: "~/.npm"
        key: npm-${{ runner.os }}-${{ hashFiles('./package-lock.json') }}

    - name: Run Fuzz Tests
      run: |
        ./npm -- clean-install
        ./npm -- run fuzz