name: Fuzz Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  fuzz:
    name: Fuzz Tests
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          auth.docker.io:443
          dl-cdn.alpinelinux.org:443
          github.com:443
          production.cloudflare.docker.com:443
          production.cloudfront.docker.com:443
          registry-1.docker.io:443
          registry.npmjs.org:443
          release-assets.githubusercontent.com:443

    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Validate Compose File
      run: docker compose --file compose.yml config --quiet

    # https://docs.docker.com/build/ci/github-actions/cache/#github-cache
    - name: Set up Docker CLI
      id: setup-buildx-action
      uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
      with:
        name: fuzz

    - name: Docker Cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: /tmp/buildkit-cache
        key: buildkit-${{ runner.os }}-${{ hashFiles('./container-images/**') }}

    - name: Build Docker images
      uses: docker/bake-action@018cb6412ab401ebaa809aa5f85966b74628600f # v7.4.0
      with:
        allow: |
          network.host
        builder: ${{ steps.setup-buildx-action.outputs.name }}
        load: true
        set: |
          *.cache-from=type=local,src=/tmp/buildkit-cache
          *.cache-to=type=local,dest=/tmp/buildkit-cache,mode=max
        source: .

    - name: NPM Cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: "~/.npm"
        key: npm-${{ runner.os }}-${{ hashFiles('./package-lock.json') }}

    - name: Run Fuzz Tests
      run: |
        ./npm -- clean-install
        ./npm -- run fuzz