name: Fuzz Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  fuzz:
    name: Fuzz Tests
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          auth.docker.io:443
          dl-cdn.alpinelinux.org:443
          github.com:443
          production.cloudflare.docker.com:443
          registry-1.docker.io:443
          registry.npmjs.org:443
          release-assets.githubusercontent.com:443

    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Validate Compose File
      run: docker compose --file compose.yml config --quiet

    # https://docs.docker.com/build/ci/github-actions/cache/#github-cache
    - name: Set up Docker CLI
      id: setup-buildx-action
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      with:
        name: fuzz

    - name: Docker Cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: /tmp/buildkit-cache
        key: buildkit-${{ runner.os }}-${{ hashFiles('./container-images/**') }}

    - name: Build Docker images
      uses: docker/bake-action@3acf805d94d93a86cce4ca44798a76464a75b88c # v6.9.0
      with:
        allow: |
          network.host
        builder: ${{ steps.setup-buildx-action.outputs.name }}
        load: true
        set: |
          *.cache-from=type=local,src=/tmp/buildkit-cache
          *.cache-to=type=local,dest=/tmp/buildkit-cache,mode=max
        source: .

    - name: NPM Cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: "~/.npm"
        key: npm-${{ runner.os }}-${{ hashFiles('./package-lock.json') }}

    - name: Run Fuzz Tests
      run: |
        ./npm -- clean-install
        ./npm -- run fuzz