name: Integration Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  readme-example-1:
    name: README Example 1
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          github.com:443

    - name: Download Bundled Artifacts
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: bundle
        path: ./

    - uses: ./
      id: preceding-tag

    - env:
        PRECEDING_TAG: ${{ steps.preceding-tag.outputs.tag }}
      run: |
        echo "Preceding tag: $PRECEDING_TAG"

  readme-example-2:
    name: README Example 2
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          github.com:443

    - name: Download Bundled Artifacts
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: bundle
        path: ./

    - uses: ./
      id: preceding-release-tag
      with:
        regex: ^release-.+$

    - env:
        PRECEDING_RELEASE_TAG: ${{ steps.preceding-release-tag.outputs.tag }}
      run: |
        echo "Preceding release tag: $PRECEDING_RELEASE_TAG"

  test:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Should return the preceding tag from a SHA.
            include-ref: ""
            ref: 7f6f9a02a5f985b460f60b8dbe6c11294695c96f
            regex: ""
            repository: ""
            expected-tag: release-0.0.0
          - name: Should return the preceding tag from a tag.
            include-ref: ""
            ref: release-0.0.2
            regex: ^release-.+$
            repository: ""
            expected-tag: release-0.0.1
          - name: Should return this tag if ref matches the filter and include-ref is set to true.
            include-ref: true
            ref: release-0.0.2
            regex: ^release-.+$
            repository: ""
            expected-tag: release-0.0.2
          - name: Should return an empty string if no preceding tag exists.
            include-ref: ""
            ref: 42371bd608bcc9ca46e0a3be0e3403571cd8d824
            regex: ""
            repository: ""
            expected-tag: ""

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          github.com:443

    - name: Download Bundled Artifacts
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: bundle
        path: ./

    - name: Run Local Action
      id: preceding-tag-local
      uses: ./
      with:
        include-ref: ${{ matrix.include-ref }}
        ref: ${{ matrix.ref }}
        regex: ${{ matrix.regex }}
        repository: ${{ matrix.repository }}

    - name: Compare Output
      env:
        EXPECTED_TAG: ${{ matrix.expected-tag }}
        OUTPUTS_TAG: ${{ steps.preceding-tag-local.outputs.tag }}
      run: |
        [ "$EXPECTED_TAG" = "$OUTPUTS_TAG" ]