name: Integration Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Get preceding tag from a SHA
            filter: ""
            ref: 7f6f9a02a5f985b460f60b8dbe6c11294695c96f
            repository: ""
            expected-tag: release-0.0.0
          - name: Get preceding tag from a tag
            filter: ""
            ref: release-0.0.2
            repository: ""
            expected-tag: release-0.0.2
          - name: Get preceding tag from a tag, ignoring the tag
            filter: ^(?!.*(release-0\.0\.2)).+$
            ref: release-0.0.2
            repository: ""
            expected-tag: release-0.0.1
          - name: No preceding tag exists
            filter: ""
            ref: 42371bd608bcc9ca46e0a3be0e3403571cd8d824
            repository: ""
            expected-tag: ""

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          github.com:443

    - name: Download Bundled Artifacts
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        name: bundle
        path: ./

    - name: Run Local Action
      id: preceding-tag-local
      uses: ./
      with:
        filter: ${{ matrix.filter }}
        ref: ${{ matrix.ref }}
        repository: ${{ matrix.repository }}

    - name: Compare Output
      env:
        EXPECTED_TAG: ${{ matrix.expected-tag }}
        OUTPUTS_TAG: ${{ steps.preceding-tag-local.outputs.tag }}
      run: |
        [ "$EXPECTED_TAG" = "$OUTPUTS_TAG" ]