name: Integration Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  readme-example-1:
    name: Readme Example 1
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          github.com:443

    - name: Download Bundled Artifacts
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: bundle
        path: ./

    - uses: ./
      id: preceding-tag

    - env:
        PRECEDING_TAG: ${{ steps.preceding-tag.outputs.tag }}
      run: |
        echo "Preceding tag: "$PRECEDING_TAG"

  readme-example-2:
    name: Readme Example 2
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          github.com:443

    - name: Download Bundled Artifacts
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: bundle
        path: ./

    - uses: ./
      id: preceding-release-tag
      with:
        filter: ^release-.+$

    - env:
        PRECEDING_RELEASE_TAG: ${{ steps.preceding-release-tag.outputs.tag }}
      run: |
        echo "Preceding release tag: "$PRECEDING_RELEASE_TAG"

  test:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Get preceding tag from a SHA
            filter: ""
            ref: 7f6f9a02a5f985b460f60b8dbe6c11294695c96f
            repository: ""
            expected-tag: release-0.0.0
          - name: Get preceding tag from a tag
            filter: ""
            ref: release-0.0.2
            repository: ""
            expected-tag: release-0.0.2
          - name: Get preceding tag from a tag, ignoring the tag
            filter: ^(?!.*(release-0\.0\.2)).+$
            ref: release-0.0.2
            repository: ""
            expected-tag: release-0.0.1
          - name: No preceding tag exists
            filter: ""
            ref: 42371bd608bcc9ca46e0a3be0e3403571cd8d824
            repository: ""
            expected-tag: ""

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          github.com:443

    - name: Download Bundled Artifacts
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: bundle
        path: ./

    - name: Run Local Action
      id: preceding-tag-local
      uses: ./
      with:
        filter: ${{ matrix.filter }}
        ref: ${{ matrix.ref }}
        repository: ${{ matrix.repository }}

    - name: Compare Output
      env:
        EXPECTED_TAG: ${{ matrix.expected-tag }}
        OUTPUTS_TAG: ${{ steps.preceding-tag-local.outputs.tag }}
      run: |
        [ "$EXPECTED_TAG" = "$OUTPUTS_TAG" ]