name: Regression Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Empty inputs
            include-ref: ""
            ref: ""
            regex: ""
            repository: ""
          - name: Filter for release-* tags
            include-ref: ""
            ref: ""
            regex: ^release-(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)$
            repository: ""
          - name: Starting from a different commit
            include-ref: ""
            ref: 7f6f9a02a5f985b460f60b8dbe6c11294695c96f
            regex: ""
            repository: ""
          - name: Using a different repository
            include-ref: ""
            ref: ""
            regex: ""
            repository: "github/markup"

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          github.com:443

    - name: Download Bundled Artifacts
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: bundle
        path: ./

    - name: Run Published Action
      id: preceding-tag-published
      uses: AJGranowski/preceding-tag-action@b308dd34c1a6ee88036f08cb40de4e0ceade1077 # v1.2.2
      with:
        include-ref: ${{ matrix.include-ref }}
        ref: ${{ matrix.ref }}
        regex: ${{ matrix.regex }}
        repository: ${{ matrix.repository }}

    - name: Run Local Action
      id: preceding-tag-local
      uses: ./
      with:
        include-ref: ${{ matrix.include-ref }}
        ref: ${{ matrix.ref }}
        regex: ${{ matrix.regex }}
        repository: ${{ matrix.repository }}

    - name: Expect Outputs To Be Equal
      env:
        LOCAL_ACTION_TAG: ${{ steps.preceding-tag-local.outputs.tag }}
        PUBLISHED_ACTION_TAG: ${{ steps.preceding-tag-published.outputs.tag }}
      run: |
        [ "$LOCAL_ACTION_TAG" = "$PUBLISHED_ACTION_TAG" ]