name: Regression Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: Regression Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        filter: []
        ref: []
        repository: []
        include:
          - filter: ""
            ref: ""
            repository: ""

    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Download Bundle Artifacts
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        name: bundle
        path: dist/

    - name: Run Local Action
      id: preceding-tag-local
      uses: ./
      with:
        filter: ${{ matrix.filter }}
        ref: ${{ matrix.ref }}
        repository: ${{ repository }}

    - name: Run Published Action
      id: preceding-tag-published
      uses: AJGranowski/preceding-tag-action@59d4a22a2e0f1d2d044eedc1cbc101e0ec6ac106 # v0.0.2
      with:
        filter: ${{ matrix.filter }}
        ref: ${{ matrix.ref }}
        repository: ${{ repository }}

    - name: Expect Outputs To Be Equal
      env:
        LOCAL_ACTION_TAG: ${{ steps.preceding-tag-local.outputs.tag }}
        PUBLISHED_ACTION_TAG: ${{ steps.preceding-tag-published.outputs.tag }}
      run: |
        [ "$LOCAL_ACTION_TAG" = "$PUBLISHED_ACTION_TAG" ]