name: Regression Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Empty inputs
            include-ref: ""
            ref: ""
            regex: ""
            repository: ""
          - name: Filter for release-* tags
            include-ref: ""
            ref: ""
            regex: ^release-(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)$
            repository: ""
          - name: Starting from a different commit
            include-ref: ""
            ref: 7f6f9a02a5f985b460f60b8dbe6c11294695c96f
            regex: ""
            repository: ""
          - name: Using a different repository
            include-ref: ""
            ref: ""
            regex: ""
            repository: "github/markup"

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          api.github.com:443
          github.com:443

    - name: Download Bundled Artifacts
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: bundle
        path: ./

    - name: Run Local Action
      id: preceding-tag-local
      uses: ./
      with:
        include-ref: ${{ matrix.include-ref }}
        ref: ${{ matrix.ref }}
        regex: ${{ matrix.regex }}
        repository: ${{ matrix.repository }}

    - name: Run Published Action
      id: preceding-tag-published
      uses: AJGranowski/preceding-tag-action@80c580ff81c21e3212bdf3e447a41837e8861bab # v0.0.6
      with:
        include-ref: ${{ matrix.include-ref }}
        ref: ${{ matrix.ref }}
        regex: ${{ matrix.regex }}
        repository: ${{ matrix.repository }}

    - name: Expect Outputs To Be Equal
      env:
        LOCAL_ACTION_TAG: ${{ steps.preceding-tag-local.outputs.tag }}
        PUBLISHED_ACTION_TAG: ${{ steps.preceding-tag-published.outputs.tag }}
      run: |
        [ "$LOCAL_ACTION_TAG" = "$PUBLISHED_ACTION_TAG" ]